### ISSUE TITLE
Add case for deficit of judges

### ISSUE THREAD

**Issue by matthewgraca** [matthewgraca/Volunteer_Scheduler#3]

**Comment by matthewgraca** [comment]
i think i need to make a round object b/c for the case of a deficit, the judge CAN judge a team they've seen before, but only for the other side... which means i need to track who's aff/neg...

**Comment by matthewgraca** [comment]
round class added. need to think about how this will change the judge class...

**Comment by anthonygraca** [comment]
I mentioned a priority queue on a different issue. It would work here too
