### ISSUE TITLE
add more functionality to getValidTeamToJudge()

### ISSUE THREAD

**Issue by matthewgraca** [matthewgraca/Volunteer_Scheduler#6]
-add preference system
-add system where they don't judge the same schools twice, but if there isn't a valid team, allow the judge to judge someone from a school they've already seen

**Comment by anthonygraca** [comment]
In data structures, you will learn of something called a "priority queue". I think that will solve both of your problems at the same time.

**Comment by matthewgraca** [comment]
-for debate type preference system, that's gonna be handled in main b/c there are multiple tournament roster lists, each with it's own debate type; so we just feed the getValidTeamToJudge(list) with the preferred list (feed in pofo list for a judge that wants only pofo, for example). for judges that don't care, maybe we can have a list in main that combines all of the lists and feeds that whole list into the function.
-added the "distinct schools" preference system
